bug-reporter:
  build: .
  command: node server.js
  volumes:
      - .:/usr/app
      - /usr/app/node_modules
  environment:
      - MONGODB_URI=<mongodburi>
      - MAIL_ADDRESS=<mail address to send report>
  ports:
    - "4000:4000"
